version: '3.7'

services:
  database:
    image: mysql:8.3
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3336:3306'
